#!/bin/sh

# get argument
arg=$1

case "$arg" in
	"setup")
		# Install luvit + lit
		curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
		mkdir bin -p
		# Move binary files
		mv luvit bin
		mv luvi bin
		mv lit bin
		# Install dependencies
		./bin/lit install
		# Install rad
		curl -OL https://github.com/simhyeon/rad/link-to-rad-not-ready-yet-for-musl
		;;
	"run")
		./bin/luvit ./main.lua
		;;
esac
